openapi: 3.0.1
info:
  title: MUSELODY API V1
  version: v1
servers:
  - url: https://{defaultHost}
    variables:
      defaultHost:
        default: https://localhost:3000/api/v1
paths:
  /articles:
    get:
      tags:
        - article
      summary: get all existing articles
      description: a big list with articles
      operationId: getAllArticles
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: "array"
                items:
                  title: "string"
            application/xml:
              schema:
                type: "array"
                items:
                  title: "string"
        "400":
          description: Invalid ID supplied
        "404":
          description: Pet not found
        "405":
          description: Validation exception
